# Generated by Django 3.1 on 2022-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierincome',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='courierweaklyincome',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reward',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transitcost',
            name='date',
            field=models.DateField(),
        ),
    ]
